POST http://localhost:4000/todo
Content-Type: application/json

{
  "user_id": 1
}

###
GET http://localhost:4000/todo/1

###
POST http://localhost:4000/todo
Content-Type: application/json

{
  "title": "제목1",
  "description": "설명1",
  "repetition": "[0]",
  "checked": false,
  "done": false,
  "user_id": 1
}

###
PUT http://localhost:4000/todo/17
Content-Type: application/json

{
  "done": true
}

###
DELETE http://localhost:4000/todo/16

###
POST http://localhost:4000/user/signin
Content-Type: application/json

{
  "email": "hello1@naver.com",
  "password": "hello1"
}

###
POST http://localhost:4000/user/signup
Content-Type: application/json

{
  "email": "hello4@naver.com",
  "password": "hello4"
}

###
PUT http://localhost:4000/user
Content-Type: application/json

{
  "id": 5,
  "email": "hello3@naver.com",
  "password": "hello3"
}

###
DELETE http://localhost:4000/user/4
