POST http://localhost:4000/todo
Content-Type: application/json

{
  "user_id": 1
}

###
GET http://localhost:4000/todo/17

###
POST http://localhost:4000/todo/add
Content-Type: application/json

{
  "title": "제목3",
  "description": "설명3",
  "repetition": "[]",
  "checked": false,
  "done": false,
  "user_id": 2
}

###
PUT http://localhost:4000/todo/17
Content-Type: application/json

{
  "done": true
}

###
DELETE http://localhost:4000/todo/18

###
POST http://localhost:4000/user/signin
Content-Type: application/json

{
  "email": "hello1@naver.com",
  "password": "hello1"
}

###
POST http://localhost:4000/user/signup
Content-Type: application/json

{
  "email": "hello5@naver.com",
  "password": "hello5"
}

###
PUT http://localhost:4000/user
Content-Type: application/json

{
  "id": 5,
  "email": "hello33@naver.com",
  "password": "hello33"
}

###
DELETE http://localhost:4000/user/6
